const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const gitService = fs.readFileSync(path.join(root, 'src', 'gitService.ts'), 'utf8');
const panelRows = fs.readFileSync(path.join(root, 'src', 'panelRows.ts'), 'utf8');
const extension = fs.readFileSync(path.join(root, 'src', 'extension.ts'), 'utf8');
const { compactCommitAge, commitRow } = require('../out/panelRows.js');
const { commitPatchPreviewHtml } = require('../out/richPreview.js');

assert.strictEqual(compactCommitAge('2 hours ago'), '2h', 'Commit ages should use compact hour units in rows');
assert.strictEqual(compactCommitAge('2 days ago'), '2d', 'Commit ages should use compact day units in rows');
assert.strictEqual(compactCommitAge('3 weeks ago'), '3w', 'Commit ages should use compact week units in rows');
assert.strictEqual(compactCommitAge('1 month ago'), '1mo', 'Commit ages should keep deterministic month units in rows');
assert.strictEqual(compactCommitAge('yesterday'), '1d', 'Git natural-language yesterday should remain compact');
assert.strictEqual(compactCommitAge(''), '', 'Empty commit ages should stay empty');
const renderedCommit = commitRow(false, { hash: 'abc1234', refs: 'HEAD', subject: 'Readable subject', author: 'Test Author', relativeDate: '2 hours ago', graph: '' }, 0);
assert(renderedCommit.includes('class="meta commit-meta">2h</span>'), 'Commit rows should display the compact age');
assert(renderedCommit.includes('2 hours ago'), 'Commit row tooltip should retain the full relative date');
const renderedPreview = commitPatchPreviewHtml({ title: 'Commit abc1234', hash: 'abc1234', subject: 'Readable subject', author: 'Test Author', relativeDate: '2 hours ago' }, '');
assert(renderedPreview.includes('Test Author · 2 hours ago'), 'Rich commit preview should retain the full relative date');
assert(gitService.includes('%(upstream:track)'), 'Branches must parse ahead/behind from git metadata instead of showing raw branch stdout');
assert(gitService.includes('--pretty=format:%h%x09%D%x09%s%x09%an%x09%ar'), 'Commits must fetch author/date fields for semantic UI rows');
assert(gitService.includes("git(args, workspaceRoot(), { LC_ALL: 'C', LANG: 'C' })"), 'Commit relative ages must use a stable English locale before compacting');
assert(panelRows.includes('export function branchRow(sel: boolean, branch: Branch, index: number): string'), 'Branches need a dedicated semantic renderer, not the generic raw row');
assert(panelRows.includes("export function commitRow(sel: boolean, commit: Commit, index: number, klass = ''): string"), 'Commits need a dedicated semantic renderer with independent range/copied visual classes, not the generic raw row');
assert(panelRows.includes('class="hash-pill"'), 'Commit hashes should render as VS Code-styled pills');
assert(!panelRows.includes('class="ref-chip'), 'Commit refs must not render as chips inside cramped one-line rows; they overlap real subjects in narrow sidebars');
assert(panelRows.includes('commit.refs ? ` · ${escapeHtml(commit.refs)}` :'), 'Commit refs should stay available in the title tooltip instead of burning row width');
assert(panelRows.includes('class="commit-main path"'), 'Commit rows should be compact one-line rows, matching the rest of the panels');
assert(!panelRows.includes('class="commit-block"'), 'Commit rows must not use a tall two-line block layout');
assert(panelRows.includes('const details = compactCommitAge(commit.relativeDate);'), 'Commit rows should compact only the visible age value');
assert(panelRows.includes('commit.relativeDate, commit.author'), 'Commit rows must retain the full age and author in the tooltip metadata');
assert(extension.includes(':root{--lgvs-font-size:var(--vscode-font-size);'), 'List typography should derive from the VS Code font-size token');
assert(extension.includes('.meta{opacity:.68') && extension.includes('font-size:var(--lgvs-meta-size)'), 'List metadata should use a responsive compact scale instead of fixed 10/11px text');
assert(extension.includes('.cursor{width:5px;'), 'All list cursors should use the reduced left column');
assert(extension.includes('.commit-row{grid-template-columns:5px 40px minmax(0,1fr) max-content;'), 'Commit CSS should keep one normal-height row with a reduced cursor/hash column and right-aligned age');
assert(!extension.includes('height:34px'), 'Commit rows must not force a taller two-line height');
assert(panelRows.includes('class="ref-kind"'), 'Branch kind/current marker should render as a compact UI badge');
assert(extension.includes('branchRow(active && i===this.branchSelected, b, i)'), 'Branches panel must use the semantic branch row renderer');
assert(extension.includes('commitRow(active && i===this.commitSelected, c, i,'), 'Commits panel must use the semantic commit row renderer with range/copied state');
assert(extension.includes('var(--vscode-editorInlayHint-background)'), 'Ref list styling should use VS Code theme tokens, not hardcoded custom colors');
assert(extension.includes('var(--vscode-list-activeSelectionBackground)'), 'Ref list selection should stay native VS Code list-themed');
assert(!extension.includes("row(active && i===this.commitSelected, 'commit', c.hash, c.subject, compactRefs(c.refs), i)"), 'Commits must not regress to hash/subject/raw-meta generic rows');

console.log('refListUx tests passed');
