const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const extension = fs.readFileSync(path.join(root, 'src', 'extension.ts'), 'utf8');
const lazygitConfig = fs.readFileSync(path.join(root, 'src', 'lazygitConfig.ts'), 'utf8');
const pkg = fs.readFileSync(path.join(root, 'package.json'), 'utf8');

assert(lazygitConfig.includes("recentRepos: '<enter>'") || extension.includes("key: '<enter>', label: '$(repo) Switch to workspace repository'"), 'Status repo switching must preserve lazygit Status recentRepos=<enter> behavior');
assert(extension.includes('async function discoverWorkspaceRepositories(): Promise<WorkspaceRepository[]>'), 'LGVS must discover available Git repositories inside the VS Code workspace');
assert(extension.includes("repoRootFor(folder.uri.fsPath)"), 'Workspace folder Git roots must be included in the Status repository selector');
assert(extension.includes("findFiles('**/.git/HEAD'"), 'Nested workspace repositories must be discovered without shelling out through find/grep');
assert(extension.includes("if (panel === 'status') return this.recentReposMenu();"), 'Enter on 1 Status must open the repository selector, matching lazygit original recent repos behavior');
assert(extension.includes('class StatusTreeProvider implements vscode.TreeDataProvider<vscode.TreeItem>'), '1 Status should use a native compact TreeView instead of a tall webview');
assert(extension.includes("vscode.window.createTreeView(VIEW_IDS.status, { treeDataProvider: statusProvider })"), '1 Status must be registered as a native TreeView');
assert(!extension.includes("registerWebviewViewProvider(VIEW_IDS.status"), '1 Status must not be registered as a webview; webviews keep too much empty vertical space');
assert(pkg.includes('\"id\": \"lazygitvs.statusView\"') && pkg.includes('\"visibility\": \"hidden\"'), '1 Status should default hidden and materialize only when the user presses 1');
assert(pkg.includes('\"when\": \"lazygitvs.statusViewVisible\"'), '1 Status should disappear again when focus leaves panel 1');
assert(extension.includes("executeCommand('setContext', 'lazygitvs.statusViewVisible', viewPanel === 'status')"), 'LGVS must drive Status visibility from active focus panel, not leave 1 Status stuck open');
assert(extension.includes('await this.updateActiveViewContext();\n    this.requestWebviewAutoFocus();'), 'Panel focus must await active-view context before revealing the native Status tree');
assert(extension.includes('await Promise.all([\n      vscode.commands.executeCommand'), 'Status visibility context updates must be awaitable instead of fire-and-pray');
assert(extension.includes('statusTreeItems(): vscode.TreeItem[]'), '1 Status must render the workspace repositories as native tree rows');
assert(extension.includes("item.command = { command: 'lazygitvs.statusEnter', title: 'Select repository', arguments: [repo.path] };"), 'Status repo rows must be selectable with Enter');
const keybindings = JSON.parse(pkg).contributes.keybindings;
assert(keybindings.some(binding => binding.key === 'enter' && binding.command === 'lazygitvs.statusEnter' && binding.when === 'focusedView == lazygitvs.statusView'), 'Pressing 1 then Enter must select/open the focused Status repository row');
assert(extension.includes("item.description = isCurrent ? `${repo.branch} · current` : repo.branch;"), '1 Status must mark the active repository row as current');
assert(extension.includes("if (isCurrent) item.iconPath = new vscode.ThemeIcon('check');"), '1 Status must visually mark the active repository row');
assert(extension.includes('qp.activeItems = items.filter(item => item.repo.path === current).slice(0, 1);'), 'Repository QuickPick must open with the current repository selected so Enter confirms it');
assert(extension.includes("qp.title = 'Recent repositories';"), 'Repository selector title should mirror lazygit original wording');
assert(extension.includes("if (!activeWorkspaceRoot || !roots.has(activeWorkspaceRoot)) activeWorkspaceRoot = roots.keys().next().value"), 'Active repo must reset when the workspace repo set changes, not cling to a stale previous root');
assert(extension.includes('activeWorkspaceRoot = repo.path'), 'Selecting a repository must switch the active Git root used by LGVS commands');
assert(extension.indexOf('this.workspaceRepos = await discoverWorkspaceRepositories().catch(() => []);') < extension.indexOf('this.files = await changedFiles(this.lazygitGit);'), 'Refresh must discover workspace repos before Git status so nested/non-root repos can become the active root');
const dogfoodUi = fs.readFileSync(path.join(root, 'scripts', 'dogfood-ui.js'), 'utf8');
assert(dogfoodUi.includes('const secondaryRepo = `${dir}-other-repo`;'), 'Dogfood must create a second repository so Status selection is testable for real');
assert(dogfoodUi.includes('secondaryFixtureRepo(fixture)'), 'Dogfood must launch VS Code with the second repository as another workspace folder');
assert(dogfoodUi.includes("OTHER_REPO_SENTINEL.md"), 'Dogfood second repo must have a unique changed file that proves LGVS switched roots');
assert(dogfoodUi.includes("Status Enter switches from the current repository row to other-repo"), 'Dogfood must press 1, move to the other repo row, press Enter, and verify current repo changes');
assert(dogfoodUi.includes("Files panel shows the selected repository changes after Status Enter"), 'Dogfood must verify Files reflects the selected repository, not only the Status label');
assert(dogfoodUi.includes("Moving from 1 Status to 2 Files hides Status again"), 'Dogfood must prove 1 Status disappears when focus leaves panel 1');
assert(extension.includes("const item = new vscode.TreeItem(path.basename(workspaceRoot()), vscode.TreeItemCollapsibleState.None);"), '1 Status must show one compact repo-name row without noisy enter text');
assert(!extension.includes("const item = new vscode.TreeItem('enter', vscode.TreeItemCollapsibleState.None);"), '1 Status must not render enter as visible row text');
assert(!extension.includes('<div class="lg-logo">lazygit</div>'), '1 Status must not render a large dashboard/logo in the sidebar');
assert(!extension.includes('All branches log'), '1 Status sidebar must not advertise a/A all-branches actions; lazygit original does not show those on-screen in Status');
assert(!extension.includes("row(false, staged ? 'staged' : '', 'staged', String(staged))"), '1 Status must not show invented staged/changed/new metrics');
assert(extension.includes("private activePanel: Panel = 'files';"), 'LazyGitVS should default to Files so 1 Status stays collapsed until explicitly focused');
assert(!extension.includes("row(false, '', 'gui'"), '1 Status must not dump internal gui config rows');

console.log('statusRepoSelection tests passed');
